### ISSUE TITLE
rumble

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/MobControlJava#10]
There is an API we can use for Android:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate

The server will send something like {leftMagnitude: 0.5, rightMagnitude: 0.0, duration_ms: 500}

Not sure what do with magnitudes since the API doesnt support that.  Could maybe create a pattern to simulate somehow.

For iOS I think the only way to do it is native wrapper with Apache Cordova.

**Comment by Nockm** [comment]
Sounds good, maybe there can be a button on the Swing UI that sends a
vibrate request.

**Comment by electronstudio** [comment]
There already is

**Comment by Nockm** [comment]
Bonzer! I'm having trouble receiving messages back though, I've attempted to log all socket events @ 1a4096dca3765345300c53d6fd8a55f61fd9cfdb.

`onopen` and `open` work fine but I don't see any `onmessage` when clicking the rumble button.

**Comment by electronstudio** [comment]
ah i havent written the server code yet.  i was just pointing out the button has been there since the beginning.

**Comment by electronstudio** [comment]
i'm happy to mark this done, unless you want to improve it further.
