### ISSUE TITLE
Support joypad graphic overlay

### ISSUE THREAD

**Issue by Nockm** [electronstudio/MobControlJava#3]
The client displays the raw hitbox graphic, which is not aesthetically pleasing; it should display something nice instead.

**Comment by electronstudio** [comment]
If you approve of the layout in 9803b76 we can proceed to draw something nicer on top of that layout.

**Comment by Nockm** [comment]
Looks good. Your layout includes axis-based input; initial support has been added for that in 6c460b5f30c61a25e6c23b557f2c78351cf37cb4.

**Comment by electronstudio** [comment]
i drew something in bf49f2e . it's not properly aligned or anything.

**Comment by Nockm** [comment]
Controller graphic is now displayed, instead of the hitbox in ffde76639d2a0114885595ac65e590cea6783737.
