### ISSUE TITLE
Show error message if WebSocket fails to connect

### ISSUE THREAD

**Issue by Nockm** [electronstudio/MobControlJava#4]

**Comment by electronstudio** [comment]
and more importantly if socket gets disconnected.  perhaps a red/green indicator to show if currently connected?

**Comment by electronstudio** [comment]
also, either have a connect button, or maybe better just keep trying to re-connect automatically every second.

**Comment by electronstudio** [comment]
currently if the websocket is idle for 30 seconds, Jetty disconnects it.  i have tried to override this but not suceeded so far.  but having auto-reconnect would fix it anyway.

**Comment by electronstudio** [comment]
we're now showing errors in the logs, and we are doing auto-reconnect.  might be nice to have a small red/yellow/green indicator for the user but not sure if it's useful so this is low priority.

**Comment by Nockm** [comment]
During attempting to reconnect, a notification is visible on the top.

This is done via logger.js which now supports setting a notification message. I should probably rename Logger to something else now that it seems to be some sort of messaging hub.
