### ISSUE TITLE
Server can’t run on Linux

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/MobControlJava#6]
Linux doesn’t allow user processes to use port 80. We can use an alternative like 8080 on Linux, but that might need changes in the JS?

**Comment by Nockm** [comment]
Sounds like a change of :https://github.com/electronstudio/MobControlJava/blob/7dbb9b1a1a7e2414c58cf0a036bb14466ec405fb/src/main/resources/client/index.js#L11

```
From: const ADDRESS = `${new URL(window.location.href).hostname}/mobcontrol/`;
To:   const ADDRESS = `${new URL(window.location.href).hostname}:8080/mobcontrol/`;
```

Although I remember the original version having the port specified, but for some reason Safari didn't like it?

**Comment by electronstudio** [comment]
Safari mobile seems ok with it now
