### ISSUE TITLE
Add web app manifest

### ISSUE THREAD

**Issue by Nockm** [electronstudio/MobControlJava#7]
https://developers.google.com/web/fundamentals/web-app-manifest

**Comment by electronstudio** [comment]
I added one, combining all the elements recommended by a couple of different online generators.  Have not tested it at all so you should probably have a look.

**Comment by electronstudio** [comment]
So it seems ok, but Chrome still doesnt consider us a 'proper' web app because we dont have a service worker because we dont have HTTPS.  I think the best we can do it pop up a reminder to tell user to add us to homescreen.

**Comment by Nockm** [comment]
A popup can be shown via:

https://github.com/electronstudio/MobControlJava/blob/352007be39d298ef497c69e5c628ee76f86fbf6c/src/main/resources/client/lib/logger.js#L24-L27

Although it might not be ready yet, as we probably want a button to dismiss the notification which hasn't been implemented yet.
